import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import User from './Props/User';
import Password from './Conditional Rendering/Password';
import Lists from './Lists';
import { Expressions } from './Expressions';
import Props from './Props/Props';
import Products from './Conditional Rendering/Products';
import Style from './Styling/Style';
import Bootstrap from './Styling/Bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar } from 'react-bootstrap';
import NavbarU from './Styling/Navbar';
import index from './Tailwind/index.css'; 
import Tailwind from './Tailwind/Tailwind';
import { Icon } from './React-Icons/Icon';
import { Event } from './Events/Event';
import {CopyEvent} from './Events/CopyEvent';
import {HoverEvent} from './Events/HoverEvent';